# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

workspace 'SimpleLoginWorkspace'
project 'SimpleLogin.xcodeproj'

target 'SimpleLogin' do
  # Pods for SimpleLogin
  pod 'module_a', :path => '../module_a'
end
